### ISSUE TITLE
Agenda items should also have a date

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/CouncilTag-Django#23]
http://council-tag.herokuapp.com/api/tag/Learning/agenda/items

I do not see any type of date as queried in the agenda items

**Comment by hungrymonkey** [comment]
querying url by agendas does provide the meeting time. However, querying by tag doesnt

https://council-tag.herokuapp.com/api/agendas/

**Comment by eselkin** [comment]
#25 addresses this, adds meeting_time field, but not merged from master to prod yet.
