### ISSUE TITLE
agenda > items > list  should also have pagenation or limit query

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/CouncilTag-Django#38]
https://council-tag.herokuapp.com/docs/

```
'http://council-tag.herokuapp.com/api/tag/${tagName}/agenda/items?format=json';
```

do we have pagination for this query?

https://github.com/hackla-engage/CouncilTag-Django/issues/5

**Comment by eselkin** [comment]
Can now use #57 ?offset=x&limit=y query params
Please use backend.engage.town
