### ISSUE TITLE
Setup heroku hosting service stay up

### ISSUE THREAD

**Issue by dorachan2000** [hackla-engage/CouncilTag-Django#4]
Django server hosted on heroku currently sleeps after 30min of inactivity and needs some sort of way to keep itself up.

Reference for the free plan
https://www.heroku.com/pricing

I suggest setting up another heroku service to ping each other using cronjob or some web server

**Comment by ShariqT** [comment]
Setup a temporary account with uptimerobot.com to ping the server every 15 minutes
