### ISSUE TITLE
Setup pagination for /agendas

### ISSUE THREAD

**Issue by dorachan2000** [hackla-engage/CouncilTag-Django#5]
Currently the /api/agendas endpoint returns a huge chunk of the agendas as a json.
Can we add pagination or some query parameters so consumers can have more selective data?

https://council-tag.herokuapp.com/api/agendas

**Comment by dstrodtman** [comment]
@dorachan2000 How do you need the data structured in order to be consumed? Also, are we planning on filtering everything by date so that only upcoming topics are appearing in the user's feed, or do we want to also show past/archived items?

**Comment by dorachan2000** [comment]
How about we keep it simple for now and add `limit`, `start` and `order` parameter in the url so consumers can get the "five" "most recent" agendas and continue to get rest of agendas with "start" parameter. 

sending GET request to the following

`/api/agendas?limit=5&start=5&order=time"`

would return something like
```
{
    "_links": {
        "next": "/api/agendas?limit=5&start=10",
        "prev": "/api/agendas?limit=5&start=0",
    },
    "limit": 5,
    "results": [
    {
        "id": 1,
        "items": [
            {
                "id": 5,
                "recommendations": [
                    {
                        "id": 9,
                        "recommendation": "sustainability strategy.",
                        "agenda_item": 5
                    }
                ],
                "title": "Strategy for Long-Term Economic Sustainability",
                "department": "Housing and Economic Development",
                "agenda": 1,
                "tags": [ 4 ]
            }
        ]
    }, ...
}
```

Default values would be nice too, so hitting `/api/agendas` would just assume `limit = 5`, `order = time` and return the 5 most recent agendas(aka 10 weeks worth of agendas)

**Comment by ShariqT** [comment]
django restframework comes with a pagination class ready to use. 
http://www.django-rest-framework.org/api-guide/pagination/

**Comment by ShariqT** [comment]
This is done in commit 9dd40913f48adeeb8ecd5ef5ad2a212f28cafc48
