### ISSUE TITLE
Tag api server is missing both icons and description.

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/CouncilTag-Django#9]
https://counciltag.docs.apiary.io/#reference/0/tags/list-tags

A sample from tags.

```
[
  {
    "id": 1,
    "name": "Community"
  },
  {
    "id": 2,
    "name": "Learning"
  },
  {
    "id": 3,
    "name": "Health"
  },
  {
    "id": 4,
    "name": "Economic Opportunity"
  }]
```

As shown in the figma app, the api server needs a way to provide icons and description.

<img width="1981" alt="screen shot 2018-01-31 at 7 27 46 pm" src="https://user-images.githubusercontent.com/771339/35659759-df3f5b24-06bc-11e8-8d8f-2d869b42a3ce.png">

Icons may be standardize another way, but description should be provided somehow.

**Comment by ShariqT** [comment]
this is done with commit 8df0a797df3dd705c87570ac9c68458380f894c0
